dubbo:
  application.name: user-b
  registry.address: zookeeper://127.0.0.1:2181
  protocol:
    name: dubbo
    port: 8082

hmily.support.rpc.annotation: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/java1?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    hikari:
      username: root
      password: root
